### ISSUE TITLE
[4.0.37] TypeError: Cannot read property 'Promise' of undefined

### ISSUE THREAD

**Issue by WayneUong** [paypal/paypal-checkout#141]
Uncaught TypeError: Cannot read property 'Promise' of undefined
    at Object.../node_modules/xo-buttonjs/public/js/button/index.js (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:2784:69)
    at __webpack_require__ (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:10:27)
    at Object.0 (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:21:23)
    at __webpack_require__ (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:10:27)
    at 0 (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:17:12)
    at https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:18:3

**Comment by WayneUong** [comment]
Just realized 37 is not deployed yet (:

**Comment by bluepnume** [comment]
Oh good catch. 4.0.37 should be deployed now. Thanks for the heads up.
