### ISSUE TITLE
For 4xx errors with json, error should be logged to the console

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#203]
Right now because the thing being thrown is the response, the error just looks like this:

```Component error: Error: Error: [object XMLHttpRequest]
Error: [object XMLHttpRequest]
    at Object.postrobot_message_response (http://bluesuncorp.co.uk/icv4/dist/checkout.js:3370:40)
    at receiveMessage (http://bluesuncorp.co.uk/icv4/dist/checkout.js:1491:55)
    at messageListener (http://bluesuncorp.co.uk/icv4/dist/checkout.js:1509:13)
    at Object.postrobot_message_response (https://www.paypalobjects.com/api/checkout.js:3368:40)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:1493:55)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:1511:13)
```

**Comment by bluepnume** [comment]
Fixed.
