### ISSUE TITLE
getParentTemplate is not a function error on payment create

### ISSUE THREAD

**Issue by jamacon36** [paypal/paypal-checkout#311]
When creating a payment in a sandbox environment the getParentTemplate function us not defined, causing the following error:

```"Error: _this20.getParentTemplate is not a function
TypeError: _this20.getParentTemplate is not a function
    at Object.onSuccess (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:9346:40)
    at _loop2 (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:1077:62)
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:1107:29)
    at SyncPromise.then (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:1125:18)
    at Function.syncPromiseTry [as try] (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:1170:42)
    at DelegateComponent.openContainer (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:9342:55)
    at Object.onSuccess (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:8556:35)
    at _loop2 (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:1077:62)
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:1107:29)
    at SyncPromise.then (https://www.paypalobjects.com/api/checkout.js?ver=4.7.4:1125:18)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2021:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:1928:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:1948:13)"

**Comment by bluepnume** [comment]
Can you let me know:

- Browser version
- `paypal.version` in your console

Could you also try without `?ver=4.7.4` on the checkout.js url, as this is going to affect our server-side caching.

**Comment by jamacon36** [comment]
Browser version: 57.0.2987.133
`paypal.version`: 4.0.47

Removing `?ver=4.7.4` did it. It's standard, read: sometimes annoying, WP behavior.

**Comment by bluepnume** [comment]
Cool, glad that fixed it. I'm going to try to make sure adding query params don't result in getting old versions of checkout.js, gotta figure out that change out in our caching layer.
