### ISSUE TITLE
Server Side Express Checkout using REST doesn't work well on DOT-NET

### ISSUE THREAD

**Issue by roukfa** [paypal/paypal-checkout#398]
Hi, I've a problem with the integration of express checkout on my MVC App.
This is script used in the client side : 
```
<script>
        paypal.Button.render({

            env: 'sandbox', // sandbox | production

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function () {
                

                // Set up a url on your server to create the payment
                var CREATE_URL = '/Home/createPayment';
                

                // Make a call to your server to set up the payment
                return paypal.request.post(CREATE_URL)
                    .then(function (res) {
                        window.alert('Payment Complete!');
                        return res.paymentID;
                    });
            },

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {

                // Set up a url on your server to execute the payment
                var EXECUTE_URL = '/Home/executePayment/';

                // Set up the data you need to pass to your server
                var data = {
                    paymentID: data.paymentID,
                    payerID: data.payerID
                };

                // Make a call to your server to execute the payment
                return paypal.request.post(EXECUTE_URL, data)
                    .then(function (res) {
                        window.alert('Payment Complete!');
                    });
            }

        }, '#paypal-button-container');
    </script>
```

This is my function createPayment. It creates the payment and turns back the payment.id in the Json format : 

 ```
public JsonResult createPayment()
        {
            var payment = PaypalTransactions.createPayment();
            return Json(payment.id, JsonRequestBehavior.AllowGet);
        }
```

This is my function executePayment. It takes two parameters : paymentId and the payerId. These parameters are sent by PayPal API when the client finished his payment : 
```
    [HttpPost]
        public ActionResult executePayment(string paymentId,string PayerID)
        {
            // Authenticate with PayPal
            var config = ConfigManager.Instance.GetProperties();
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);

            var payment = new PaypalTransactions();
            PaypalTransactions.ExecutePayment(PayerID);

            return View();
        }
```
It doesn't work, I got this log : 
```
ppxo_unhandled_error Objectcountry: "US"env: "sandbox"errtype: "[object Error]"host: "www.sandbox.paypal.com"lang: "fr"pageID: "46e69335f4"path: "/webapps/hermes/button"referer: "http://localhost:59679"stack: "Error: No value passed to payment↵    at https://www.paypalobjects.com/api/checkout.js:7986:52↵    at https://www.paypalobjects.com/api/checkout.js:7417:54↵    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)↵    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)↵    at https://www.paypalobjects.com/api/checkout.js:7363:48↵    at https://www.paypalobjects.com/api/checkout.js:7417:54↵    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)↵    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)↵    at https://www.paypalobjects.com/api/checkout.js:7440:42↵    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)↵    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2471:118)↵    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2369:77)↵    at messageListener (https://www.paypalobjects.com/api/checkout.js:2390:13)"timestamp: 1499128843681uid: "66ae02c38a"ver: "4.0.89"windowID: "3fb734d342"__proto__: Object
__WEBPACK_IMPORTED_MODULE_5__window__.g.window.console.window.console.(anonymous function) @ index.js:544
exceptions.js:14 Uncaught Error: No value passed to payment
    at https://www.paypalobjects.com/api/checkout.js:7986:52
    at https://www.paypalobjects.com/api/checkout.js:7417:54
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)
    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)
    at https://www.paypalobjects.com/api/checkout.js:7363:48
    at https://www.paypalobjects.com/api/checkout.js:7417:54
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)
    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)
    at https://www.paypalobjects.com/api/checkout.js:7440:42
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)
    at https://www.paypalobjects.com/api/checkout.js:7986:52
    at https://www.paypalobjects.com/api/checkout.js:7417:54
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)
    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)
    at https://www.paypalobjects.com/api/checkout.js:7363:48
    at https://www.paypalobjects.com/api/checkout.js:7417:54
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)
    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)
    at https://www.paypalobjects.com/api/checkout.js:7440:42
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2471:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2369:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2390:13)
```

Thank you for your help!

**Comment by bluepnume** [comment]
So, you're passing back `payment.id` as a string:

```dotnet
return Json(payment.id, JsonRequestBehavior.AllowGet);
```

Then on your front-end you're trying to access the `paymentID` property:

```javascript
                return paypal.request.post(CREATE_URL)
                    .then(function (res) {
                        return res.paymentID;
                    });
```

Can you try adding a `console.log(res)`? My suspicion is, since you're just returning the payment ID directly, you can just return the response:

```javascript
                return paypal.request.post(CREATE_URL)
                    .then(function (res) {
                        return res;
                    });
```

**Comment by swordz36** [comment]
What are you setting your Redirect_url to? 
![image](https://user-images.githubusercontent.com/17201265/28189732-d948b3b0-67ec-11e7-8eae-e940d0f2947d.png)
I am doing this but it is not working

**Comment by bluepnume** [comment]
Hi @swordz36 

As requested, can you try `console.log(res)` and tell me what you see?

```
                return paypal.request.post(CREATE_URL)
                    .then(function (res) {
                        console.log('Res:', res);
                    });
```

**Comment by NgKengFai** [comment]
doesnt work on localhost. when i pushed to live server it worked. I have the exact error Error: No value passed to payment

**Comment by bluepnume** [comment]
@NgKengFai can you please open a new issue and share your code?

**Comment by NgKengFai** [comment]
It's okay during live but not localhost
