### ISSUE TITLE
PayPal express checkout window doesn't open

### ISSUE THREAD

**Issue by coderintherye** [paypal/paypal-checkout#517]
### Description

paypal version: 4.0.146
browser: Chrome 61.0.3163.100 (though happens in multiple browsers)
link: https://www.kiva.org/portfolio/credit/deposit or https://www.kiva.org/lend (choose a loan then checkout)
console error:
Uncaught Error: Timed out waiting 10000ms for payment
    at ParentComponent.<anonymous> (https://www.paypalobjects.com/api/checkout.js:8859:230)
    at Object.resultValue (https://www.paypalobjects.com/api/checkout.js:6095:41)
    at https://www.paypalobjects.com/api/checkout.js:3410:40
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8257:37)
    at Object.handler (https://www.paypalobjects.com/api/checkout.js:3409:77)
    at https://www.paypalobjects.com/api/checkout.js:2836:32
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8257:37)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_request] (https://www.paypalobjects.com/api/checkout.js:2832:70)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2765:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2786:13)
    at i (https://www-kiva-org.global.ssl.fastly.net/rgit2f22ac049d0cd372767110491df6e93077b1b70d/www_kiva/client/dist/app.bundle.js:101:15268)
    at nrWrapper (https://www.kiva.org/portfolio/credit/deposit:13:11651)
    at ParentComponent.<anonymous> (https://www.paypalobjects.com/api/checkout.js:8859:230)
    at Object.resultValue (https://www.paypalobjects.com/api/checkout.js:6095:41)
    at https://www.paypalobjects.com/api/checkout.js:3410:40
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8257:37)
    at Object.handler (https://www.paypalobjects.com/api/checkout.js:3409:77)
    at https://www.paypalobjects.com/api/checkout.js:2836:32
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8257:37)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_request] (https://www.paypalobjects.com/api/checkout.js:2832:70)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2765:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2786:13)
    at i (https://www-kiva-org.global.ssl.fastly.net/rgit2f22ac049d0cd372767110491df6e93077b1b70d/www_kiva/client/dist/app.bundle.js:101:15268)
    at nrWrapper (https://www.kiva.org/portfolio/credit/deposit:13:11651)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2863:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2765:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2786:13)

Does the issue also occur at [developer.paypal.com/demo/checkout]: No

Does the issue occur consistently, or intermittently: Consistent

### Steps to reproduce

Click on Express checkout button. Get console error. See screen flicker but checkout window doesn't open.

**Comment by coderintherye** [comment]
Loading again, albeit very slowly. Closing.

**Comment by coderintherye** [comment]
Re-opening as seeing it again. There have been no changes on our side.
@bluepnume could this have anything to do with https://github.com/paypal/paypal-checkout/commit/6f7ab2f6c3dc5ab660210b561e5efd1ed4ffbea0 ?

**Comment by coderintherye** [comment]
@bluepnume Unless I'm mistaken, it looks like you went from a timeout of 10,000 to 50?

**Comment by bluepnume** [comment]
Can you please clear your browser cache and try once more? You should see version 1.0.148.

**Comment by coderintherye** [comment]
Thanks @bluepnume yes after clearing cache and getting to 148 it is now working
