### ISSUE TITLE
PayPal checkout iframe throwing errors on IE 11 Windows 8

### ISSUE THREAD

**Issue by danielkyh** [paypal/paypal-checkout#536]
### Description

Please provide a short description of the issue here, along with:
We are having issues for users using IE 11 on windows 8.  Clicking the PayPal checkout button throws an javascript error, and no new window is opened.

![dashboard](https://user-images.githubusercontent.com/12974101/33032789-8974d73e-cddf-11e7-83c2-64dce693ac95.png)

Error thrown is as follows
`Error: Can not open popup window - Error: Unspecified error.
   at window.open (https://www.paypalobjects.com/api/checkout.js:2443:13)
   at popup (https://www.paypalobjects.com/api/checkout.js:7591:17)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5742:25)
   at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8840:21)
   at RENDER_DRIVERS[].open (https://www.paypalobjects.com/api/checkout.js:5733:17)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:6191:21)
   at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8840:21)
   at ParentComponent.prototype.open (https://www.paypalobjects.com/api/checkout.js:6187:17)
   at descriptor.value (https://www.paypalobjects.com/api/checkout.js:7532:60)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5938:21)`

Browser version this is being tested on is Internet Explorer 11.0.9600

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [X] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by danielkyh** [comment]
I simulated through BrowserStack which I assume has default settings.  This is on Windows 8.1 if that helps in anyway.  No special addons I am aware of.

**Comment by bluepnume** [comment]
Can you try this once more? I wasn't able to repro, but I've implemented a generic fallback for window.open failures. I may still need your help debugging but I'm hoping this patch should help in the short term.

(Please make sure you clear your cache and console.log(paypal.version) shows at least 4.0.167)

**Comment by dneighbors** [comment]
This did fix the issue.  We are no longer able to re-create in our production environment or on PayPal developer test site. 👍
