### ISSUE TITLE
IE button render - "Bridge url needed to render popup"

### ISSUE THREAD

**Issue by thomlan** [paypal/paypal-checkout#538]
### Description
Using client API, unable to render a button in IE. Works fine in Firefox. 

IE 11 console shows: 

`ppxo_unhandled_error {"stack":"Error: Bridge url needed to render popup\n   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:6181:134)\n   at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8840:21)\n   at ParentComponent.prototype.openBridge (https://www.paypalobjects.com/api/checkout.js:6167:17)\n   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5961:25)\n   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8707:33)\n   at ZalgoPromise.prototype.dispatch (https://www.paypalobjects.com/api/checkout.js:8704:26)\n   at ZalgoPromise.prototype.then (https://www.paypalobjects.com/api/checkout.js:8749:17)\n   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5960:21)\n   at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8840:21)\n   at ParentComponent.prototype.tryInit (https://www.paypalobjects.com/api/checkout.js:6596:17)","errtype":"[object Error]","timestamp":1511298371311,"windowID":"96f61db672","p ...`

Referencing https://www.paypalobjects.com/api/checkout.js in an ASP.NET WebForms application on a child form.
Issue is constant for IE, doesn't happen in Edge browser.
Using meta tag <meta http-equiv="X-UA-Compatible" content="IE=edge" /> as required.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Strange. Can you confirm the version of checkout.js you're using? I'm not personally able to repro.

**Comment by tobsn** [comment]
We're having the same issue!

IE11 and I caught a single "Microsoft Edge 13" (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586) - the user agents for IE11 are pretty random so I assume its not a extension issue or similar:

```
Error: Bridge url needed to render popup
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:6181:134)
   at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8840:21)
   at ParentComponent.prototype.openBridge (https://www.paypalobjects.com/api/checkout.js:6167:17)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5961:25)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8707:33)
   at ZalgoPromise.prototype.dispatch (https://www.paypalobjects.com/api/checkout.js:8704:26)
   at ZalgoPromise.prototype.then (https://www.paypalobjects.com/api/checkout.js:8749:17)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5960:21)
   at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8840:21)
   at ParentComponent.prototype.tryInit (https://www.paypalobjects.com/api/checkout.js:6596:17)
```

I see a few on IE10 as well with this trace:

```
Error: Bridge url needed to render popup
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:6181:134)
   at try (https://www.paypalobjects.com/api/checkout.js:8840:21)
   at openBridge (https://www.paypalobjects.com/api/checkout.js:6167:17)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5961:25)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8707:33)
   at dispatch (https://www.paypalobjects.com/api/checkout.js:8704:26)
   at then (https://www.paypalobjects.com/api/checkout.js:8749:17)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:5960:21)
   at try (https://www.paypalobjects.com/api/checkout.js:8840:21)
   at tryInit (https://www.paypalobjects.com/api/checkout.js:6596:17)
```


It's definitely an IE only issue.

**Comment by bluepnume** [comment]
@tobsn / @thomlan -- can you share a url where I can try your integration?

**Comment by tobsn** [comment]
@bluepnume can I somehow message you directly?
