### ISSUE TITLE
actions.restart() not working with popupBridge.js

### ISSUE THREAD

**Issue by edbird-pp** [paypal/paypal-checkout#603]
### Description

When using a native SDK (e.g. https://github.com/braintree/popup-bridge-ios) alongside checkout.js to support a native experience launched from a WebView, there are certain issues arising. The main one is support for actions.restart which currently throws an error.

```
logger.js:65 ppxo_unhandled_error Object {stack: "Error: TypeError: Cannot read property 'then' of u…://www.paypalobjects.com/api/checkout.js:3080:13)", errtype: "[object Error]", timestamp: 1518713519380, windowID: "f1710985cf", pageID: "117ed7732a"…}
print @ logger.js:65
log @ logger.js:175
error @ logger.js:228
(anonymous) @ setup.js:29
dispatchPossiblyUnhandledError @ exceptions.js:18
(anonymous) @ promise.js:111

types.js:119 Uncaught Error: TypeError: Cannot read property 'then' of undefined
    at Object.restartFlow (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=2.0.2_20180209175845136.unx:4322:40)
    at https://www.paypalobjects.com/api/checkout.js:3712:40
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9080:37)
    at Object.handler (https://www.paypalobjects.com/api/checkout.js:3711:77)
    at https://www.paypalobjects.com/api/checkout.js:3132:32
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9080:37)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_request] (https://www.paypalobjects.com/api/checkout.js:3128:70)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3059:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3080:13)
    at Object.restartFlow (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=2.0.2_20180209175845136.unx:4322:40)
    at https://www.paypalobjects.com/api/checkout.js:3712:40
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9080:37)
    at Object.handler (https://www.paypalobjects.com/api/checkout.js:3711:77)
    at https://www.paypalobjects.com/api/checkout.js:3132:32
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9080:37)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_request] (https://www.paypalobjects.com/api/checkout.js:3128:70)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3059:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3080:13)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3160:122)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3059:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3080:13)
```

paypal.version="4.0.173"
Test site: https://ppxoab.herokuapp.com/test.html
Happens consistently and on the developer site

### Steps to reproduce

Try to use a native SDK with checkout.js and try `actions.restart()` in onAuthorize

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report, I'll take a look.
