### ISSUE TITLE
Cannot pay with PayPal with PrestaShop module

### ISSUE THREAD

**Issue by MarcoCapoferri** [paypal/paypal-checkout#628]
### Description
Receiving

`Error: Error: PayPal payment options are invalid. at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3158:31) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:77) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13)`

when clicking Pay with PayPal button

- PayPal 4.3.1 for PrestaShop installed from plugin manager
- `paypal.version = "4.0.178"`
- The exact browser version
- A link to your page with the issue, if possible
- Console logs

api.braintreegateway.com/merchants/ysycg43zmy28yyjg/client_api/v1/paypal_hermes/setup_billing_agreement Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)

checkout.js:5070 ppxo_unhandled_error Objectcountry: "IT"env: "production"errtype: "[object Error]"host: "www.paypal.com"lang: "it"pageID: "335bd16825"path: "/webapps/hermes/button"prev_corr_ids: ""referer: "https://www.relevent.it"stack: "Error: PayPal payment options are invalid.

at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3158:31)

at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:77)

at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13)"timestamp: 1520354732149uid: "b129622655_ge3dunbvhizdg"ver: "4.0.178"windowID: "ed5bd8e9bd"__proto__: Object
window.console.(anonymous function) @ checkout.js:5070
checkout.js:8825 Uncaught Error: PayPal payment options are invalid.
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3158:31)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13)

- The issue occurs consistently

### Steps to reproduce

Register to https://relevent.it and put a product into the cart.
Go to checkout and fill your data.
Select PayPal as payment method
Click PayPal button

you get the error

### Affected browsers

- [X] Chrome
- [X] Safari
- [X] Firefox
- [X] Edge
- [X] IE
- [X] Chrome Mobile/Tablet
- [X] Safari Mobile/Tablet
- [X] Web View / Safari ViewController
- [X] Other

**Comment by bluepnume** [comment]
Can you please share your code?
