### ISSUE TITLE
Error object in onError block not giving proper object to read its throwing string

### ISSUE THREAD

**Issue by sandeepkundu4344** [paypal/paypal-checkout#673]
`onError: function (err) {
                            
                              err.name;
                               
                               //SweetAlert.swal({title: err.name, text: err.details.issue, type: "error"});

                        }

`

return is string as written below:

Error: Error: Request to post https://www.paypal.com/v1/oauth2/token failed with 401 error. Correlation id: 6e1bc08b7a398, 6e1bc08b7a398

{
    "error": "invalid_client",
    "error_description": "Client Authentication failed"
}

    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:14232:39)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3192:31)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2742:60)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2763:13)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:3192:31)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2742:60)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2763:13)

as you can see json literal is wrapped with extra text which is causing error in reading this object, pls is there any fix for this ??

**Comment by 9mm** [comment]
I also am wondering this. Ive spent the last hour jsut trying to figure out how to display a simple error. Literally none of the paypal docs have any good examples...........

**Comment by 9mm** [comment]
Furthermore, it keeps closing alert boxes and such. This is so frustrating, all I want to do is show the error if either the `payment` REST api call to my server fails, or my `onAuthorize` api cal... I catch exceptions on my server, and return them as JSON. All I want to do is simply show the damn error and I've now spent almost 2 hours just trying to show the message. I have yet to find any examples online or in any documentation

**Comment by 9mm** [comment]
I also just want to show an alert() to make things simple, and about 50% of the time the alert immediately closes. i about give up up on this.

**Comment by bluepnume** [comment]
For reference: errors passed on `onError` are not really designed to be consumed by the end-users of apps. They should be logged, and a generic error message should be shown to the user.
