### ISSUE TITLE
Error: no window to focus

### ISSUE THREAD

**Issue by mrharel** [paypal/paypal-checkout#845]
### Description
user clicks on the pay button, close the popup window and click on the layer. This throws an error:
```
Error: No window to focus
at ParentComponent.focus (https://www.paypalobjects.com/api/checkout.js:5630:103)
at Object.focus (https://www.paypalobjects.com/api/checkout.js:5396:48)
at https://www.paypalobjects.com/api/checkout.js:3213:40
at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:7925:37)
at Object.handler (https://www.paypalobjects.com/api/checkout.js:3212:47)
at https://www.paypalobjects.com/api/checkout.js:2540:32
at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:7925:37)
at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_request] (https://www.paypalobjects.com/api/checkout.js:2536:40)
at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2615:60)
at messageListener (https://www.paypalobjects.com/api/checkout.js:2636:13)
at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2570:31)
at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2615:60)
at messageListener (https://www.paypalobjects.com/api/checkout.js:2636:13)

Error: Target window is closed
at https://www.paypalobjects.com/api/checkout.js:2659:60
at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:7925:37)
at request (https://www.paypalobjects.com/api/checkout.js:2641:43)
at Object._send [as send] (https://www.paypalobjects.com/api/checkout.js:2734:20)
at DelegateComponent.wrapper (https://www.paypalobjects.com/api/checkout.js:3280:33)
at DelegateComponent._this.focus (https://www.paypalobjects.com/api/checkout.js:4120:52)
at Object.focus (https://www.paypalobjects.com/api/checkout.js:5689:44)
at HTMLDivElement.focus (https://www.paypalobjects.com/api/checkout.js:8532:112)
```

![paypal](https://user-images.githubusercontent.com/473889/45091946-43d07f80-b114-11e8-8c42-4aab5fb5817a.gif)

This can be reproduced in the demo page: https://developer.paypal.com/demo/checkout/#/pattern/client

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by mcntsh** [comment]
Should be fixed with our latest release ([v4.0.233](https://github.com/paypal/paypal-checkout/tree/v4.0.233))! I just verified on our demo app that this is no longer happening.

Thanks for the report. If this issue crops up again please open up another ticket.
