### ISSUE TITLE
window.React.createClass is not a function, Cannot read property 'createClass' of undefined

### ISSUE THREAD

**Issue by leotm** [paypal/paypal-checkout#892]
I have what I mentioned earlier [here](https://github.com/paypal/paypal-checkout/issues/889) working successfully with the [Server integration](https://developer.paypal.com/docs/checkout/how-to/server-integration/).
So just refactoring to [React.js Element](https://github.com/paypal/paypal-checkout/blob/master/docs/frameworks.md#user-content-reactjs-element) taking your comment onboard.

My code:
```
import React from 'react'
import ReactDOM from 'react-dom'

;(window as any).React = React
;(window as any).ReactDOM = ReactDOM

export default (window as any).React.createClass({
  render: function() {
    let client = {
      ...
    }

    const payment = async () => {
      ...
    }

    const onAuthorize = async (data, _actions) => {
      ...
    }

    let PayPalButton = (window as any).paypal.Button.driver('react', {
      React,
      ReactDOM,
    })

    return (
      <div className="shoppingCart">
        <p>
          Buy <strong>Full Body Lobster Onesie - $24.99</strong> now!
        </p>

        <PayPalButton
          client={client}
          env={env.ENV === 'local' ? 'sandbox' : 'production'}
          payment={payment}
          commit={true}
          onAuthorize={onAuthorize}
        />
      </div>
    )
  },
})
```

But getting:
```
window.React.createClass is not a function
TypeError: window.React.createClass is not a function at Module../components/paypal/button.tsx (http://localhost:4000/_next/static/chunks/1.js:43:77) at __webpack_require__ (http://localhost:4000/_next/static/runtime/webpack.js:790:31) at fn (http://localhost:4000/_next/static/runtime/webpack.js:151:20)
```
And if I leave out:
```
;(window as any).React = React
;(window as any).ReactDOM = ReactDOM
```
I get:
```
Cannot read property 'createClass' of undefined
TypeError: Cannot read property 'createClass' of undefined at Module../components/paypal/button.tsx (http://localhost:4000/_next/static/chunks/1.js:53:77) at __webpack_require__ (http://localhost:4000/_next/static/runtime/webpack.js:790:31) at fn (http://localhost:4000/_next/static/runtime/webpack.js:151:20)
```
Any ideas?

Many thanks,

Leo

**Comment by bluepnume** [comment]
Do you have a page where we can repro?

**Comment by mcntsh** [comment]
Hey @leotm,

The reason why you are getting `Cannot read property 'createClass' of undefined` is because you're no longer assigning `React` to your window object, but you're referencing from there. Can you remove that and try again?

**Comment by mcntsh** [comment]
Closing for now. Please feel free to re-open this issue if there's an update from your side.
